from typing import List, Dict, Optional
from app.data.blue_line_stations import BLUE_LINE_STATIONS
from app.data.violet_line_stations import VIOLET_LINE_STATIONS
from app.data.orange_line_stations import ORANGE_LINE_STATIONS
from app.data.aqua_line_stations import AQUA_LINE_STATIONS

class MultiLineStationService:
    def __init__(self):
        self.yellow_line_stations = self._load_yellow_line()
        self.blue_line_stations = BLUE_LINE_STATIONS
        self.violet_line_stations = VIOLET_LINE_STATIONS
        self.orange_line_stations = ORANGE_LINE_STATIONS
        self.aqua_line_stations = AQUA_LINE_STATIONS
        self.all_stations = (
            self.yellow_line_stations + 
            self.blue_line_stations + 
            self.violet_line_stations + 
            self.orange_line_stations +
            self.aqua_line_stations
        )
    
    def _load_yellow_line(self) -> List[Dict]:
        """Load Yellow Line stations (truncated for brevity)"""
        return [
            {"id": 1, "station_id": "YL01", "name": "Samaypur Badli(First Station)", "display_name": "Samaypur Badli(First Station)", "line": "Yellow", "coordinates": {"latitude": 28.7446158, "longitude": 77.1382654}, "distance_from_origin_km": 0.0, "layout": "elevated", "opened_year": 2015, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator", "parking"], "importance_score": 7, "station_type": "mixed", "avg_crowd_multiplier": {"peak": 1.62, "offpeak": 0.66, "weekend": 0.59}},
            {"id": 2, "station_id": "YL02", "name": "Rohini Sector 18-19", "display_name": "Rohini Sector 18-19", "line": "Yellow", "coordinates": {"latitude": 28.7324, "longitude": 77.125}, "distance_from_origin_km": 1.5, "layout": "elevated", "opened_year": 2009, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator", "parking"], "importance_score": 8, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.8, "offpeak": 0.7, "weekend": 0.65}},
            {"id": 3, "station_id": "YL03", "name": "Haiderpur Badli Mor", "display_name": "Haiderpur Badli Mor", "line": "Yellow", "coordinates": {"latitude": 28.7203, "longitude": 77.1156}, "distance_from_origin_km": 3.2, "layout": "elevated", "opened_year": 2009, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 6, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.5, "offpeak": 0.6, "weekend": 0.55}},
            {"id": 4, "station_id": "YL04", "name": "Jahangirpuri", "display_name": "Jahangirpuri", "line": "Yellow", "coordinates": {"latitude": 28.7094, "longitude": 77.1043}, "distance_from_origin_km": 4.8, "layout": "elevated", "opened_year": 2009, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator", "parking"], "importance_score": 7, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.7, "offpeak": 0.65, "weekend": 0.6}},
            {"id": 5, "station_id": "YL05", "name": "Adarsh Nagar", "display_name": "Adarsh Nagar", "line": "Yellow", "coordinates": {"latitude": 28.7014, "longitude": 77.0931}, "distance_from_origin_km": 6.1, "layout": "elevated", "opened_year": 2009, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 6, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.4, "offpeak": 0.55, "weekend": 0.5}},
            {"id": 6, "station_id": "YL06", "name": "Azadpur", "display_name": "Azadpur", "line": "Yellow", "coordinates": {"latitude": 28.6936, "longitude": 77.0819}, "distance_from_origin_km": 7.4, "layout": "elevated", "opened_year": 2004, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator", "parking"], "importance_score": 8, "station_type": "commercial", "avg_crowd_multiplier": {"peak": 1.9, "offpeak": 0.8, "weekend": 0.7}},
            {"id": 7, "station_id": "YL07", "name": "Model Town", "display_name": "Model Town", "line": "Yellow", "coordinates": {"latitude": 28.6858, "longitude": 77.0707}, "distance_from_origin_km": 7.6, "layout": "underground", "opened_year": 2004, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 7, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.6, "offpeak": 0.6, "weekend": 0.55}},
            {"id": 8, "station_id": "YL08", "name": "GTB Nagar", "display_name": "GTB Nagar", "line": "Yellow", "coordinates": {"latitude": 28.6777, "longitude": 77.0596}, "distance_from_origin_km": 9.2, "layout": "underground", "opened_year": 2004, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 9, "station_type": "educational", "avg_crowd_multiplier": {"peak": 2.0, "offpeak": 0.9, "weekend": 0.5}},
            {"id": 9, "station_id": "YL09", "name": "Vishwavidyalaya", "display_name": "Vishwavidyalaya", "line": "Yellow", "coordinates": {"latitude": 28.6696, "longitude": 77.0485}, "distance_from_origin_km": 10.3, "layout": "underground", "opened_year": 2004, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 9, "station_type": "educational", "avg_crowd_multiplier": {"peak": 2.1, "offpeak": 0.95, "weekend": 0.45}},
            {"id": 10, "station_id": "YL10", "name": "Vidhan Sabha", "display_name": "Vidhan Sabha", "line": "Yellow", "coordinates": {"latitude": 28.6615, "longitude": 77.0374}, "distance_from_origin_km": 11.4, "layout": "underground", "opened_year": 2004, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 7, "station_type": "government", "avg_crowd_multiplier": {"peak": 1.5, "offpeak": 0.6, "weekend": 0.3}},
            {"id": 11, "station_id": "YL11", "name": "Civil Lines", "display_name": "Civil Lines", "line": "Yellow", "coordinates": {"latitude": 28.6534, "longitude": 77.0263}, "distance_from_origin_km": 12.1, "layout": "underground", "opened_year": 2004, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 6, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.3, "offpeak": 0.55, "weekend": 0.5}},
            {"id": 12, "station_id": "YL12", "name": "Kashmere Gate", "display_name": "Kashmere Gate", "line": "Yellow", "coordinates": {"latitude": 28.6453, "longitude": 77.0152}, "distance_from_origin_km": 13.2, "layout": "underground", "opened_year": 2002, "is_interchange": True, "interchange_lines": ["Violet", "Red"], "facilities": ["elevator", "escalator", "parking"], "importance_score": 10, "station_type": "transport_hub", "avg_crowd_multiplier": {"peak": 2.5, "offpeak": 1.2, "weekend": 1.0}},
            {"id": 13, "station_id": "YL13", "name": "Chandni Chowk", "display_name": "Chandni Chowk", "line": "Yellow", "coordinates": {"latitude": 28.6372, "longitude": 77.0041}, "distance_from_origin_km": 14.3, "layout": "underground", "opened_year": 2002, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 9, "station_type": "commercial", "avg_crowd_multiplier": {"peak": 2.2, "offpeak": 1.5, "weekend": 1.8}},
            {"id": 14, "station_id": "YL14", "name": "Chawri Bazar", "display_name": "Chawri Bazar", "line": "Yellow", "coordinates": {"latitude": 28.6291, "longitude": 76.9930}, "distance_from_origin_km": 15.3, "layout": "underground", "opened_year": 2002, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 8, "station_type": "commercial", "avg_crowd_multiplier": {"peak": 2.0, "offpeak": 1.3, "weekend": 1.5}},
            {"id": 15, "station_id": "YL15", "name": "New Delhi", "display_name": "New Delhi", "line": "Yellow", "coordinates": {"latitude": 28.6210, "longitude": 77.0819}, "distance_from_origin_km": 16.4, "layout": "underground", "opened_year": 2005, "is_interchange": True, "interchange_lines": ["Orange"], "facilities": ["elevator", "escalator", "parking", "wifi"], "importance_score": 10, "station_type": "transport_hub", "avg_crowd_multiplier": {"peak": 2.8, "offpeak": 1.5, "weekend": 1.2}},
            {"id": 16, "station_id": "YL16", "name": "Rajiv Chowk", "display_name": "Rajiv Chowk", "line": "Yellow", "coordinates": {"latitude": 28.6129, "longitude": 77.2090}, "distance_from_origin_km": 17.2, "layout": "underground", "opened_year": 2002, "is_interchange": True, "interchange_lines": ["Blue"], "facilities": ["elevator", "escalator", "parking", "wifi", "shopping"], "importance_score": 10, "station_type": "commercial", "avg_crowd_multiplier": {"peak": 3.0, "offpeak": 1.8, "weekend": 1.5}},
            {"id": 17, "station_id": "YL17", "name": "Patel Chowk", "display_name": "Patel Chowk", "line": "Yellow", "coordinates": {"latitude": 28.6048, "longitude": 77.2201}, "distance_from_origin_km": 18.5, "layout": "underground", "opened_year": 2004, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 8, "station_type": "government", "avg_crowd_multiplier": {"peak": 1.9, "offpeak": 0.7, "weekend": 0.4}},
            {"id": 18, "station_id": "YL18", "name": "Central Secretariat", "display_name": "Central Secretariat", "line": "Yellow", "coordinates": {"latitude": 28.5967, "longitude": 77.2312}, "distance_from_origin_km": 19.4, "layout": "underground", "opened_year": 2010, "is_interchange": True, "interchange_lines": ["Violet"], "facilities": ["elevator", "escalator", "parking"], "importance_score": 9, "station_type": "government", "avg_crowd_multiplier": {"peak": 2.3, "offpeak": 0.8, "weekend": 0.3}},
            {"id": 19, "station_id": "YL19", "name": "Udyog Bhawan", "display_name": "Udyog Bhawan", "line": "Yellow", "coordinates": {"latitude": 28.5886, "longitude": 77.2423}, "distance_from_origin_km": 19.7, "layout": "underground", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 7, "station_type": "government", "avg_crowd_multiplier": {"peak": 1.6, "offpeak": 0.6, "weekend": 0.3}},
            {"id": 20, "station_id": "YL20", "name": "Lok Kalyan Marg", "display_name": "Lok Kalyan Marg", "line": "Yellow", "coordinates": {"latitude": 28.5805, "longitude": 77.2534}, "distance_from_origin_km": 21.3, "layout": "underground", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 7, "station_type": "government", "avg_crowd_multiplier": {"peak": 1.5, "offpeak": 0.5, "weekend": 0.3}},
            {"id": 21, "station_id": "YL21", "name": "Jor Bagh", "display_name": "Jor Bagh", "line": "Yellow", "coordinates": {"latitude": 28.5724, "longitude": 77.2645}, "distance_from_origin_km": 22.5, "layout": "underground", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 6, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.3, "offpeak": 0.5, "weekend": 0.45}},
            {"id": 22, "station_id": "YL22", "name": "INA", "display_name": "INA", "line": "Yellow", "coordinates": {"latitude": 28.5643, "longitude": 77.2756}, "distance_from_origin_km": 23.8, "layout": "underground", "opened_year": 2010, "is_interchange": True, "interchange_lines": ["Pink"], "facilities": ["elevator", "escalator", "parking"], "importance_score": 9, "station_type": "mixed", "avg_crowd_multiplier": {"peak": 2.1, "offpeak": 0.9, "weekend": 0.8}},
            {"id": 23, "station_id": "YL23", "name": "AIIMS", "display_name": "AIIMS", "line": "Yellow", "coordinates": {"latitude": 28.5562, "longitude": 77.2867}, "distance_from_origin_km": 25.2, "layout": "underground", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator", "parking"], "importance_score": 10, "station_type": "medical", "avg_crowd_multiplier": {"peak": 2.4, "offpeak": 1.5, "weekend": 1.3}},
            {"id": 24, "station_id": "YL24", "name": "Green Park", "display_name": "Green Park", "line": "Yellow", "coordinates": {"latitude": 28.5481, "longitude": 77.2978}, "distance_from_origin_km": 26.8, "layout": "underground", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 8, "station_type": "commercial", "avg_crowd_multiplier": {"peak": 1.9, "offpeak": 0.8, "weekend": 0.7}},
            {"id": 25, "station_id": "YL25", "name": "Hauz Khas", "display_name": "Hauz Khas", "line": "Yellow", "coordinates": {"latitude": 28.5400, "longitude": 77.3089}, "distance_from_origin_km": 28.5, "layout": "underground", "opened_year": 2010, "is_interchange": True, "interchange_lines": ["Magenta"], "facilities": ["elevator", "escalator", "parking"], "importance_score": 9, "station_type": "mixed", "avg_crowd_multiplier": {"peak": 2.2, "offpeak": 1.0, "weekend": 1.2}},
            {"id": 26, "station_id": "YL26", "name": "Malviya Nagar", "display_name": "Malviya Nagar", "line": "Yellow", "coordinates": {"latitude": 28.5319, "longitude": 77.3200}, "distance_from_origin_km": 30.3, "layout": "underground", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 7, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.7, "offpeak": 0.7, "weekend": 0.65}},
            {"id": 27, "station_id": "YL27", "name": "Saket", "display_name": "Saket", "line": "Yellow", "coordinates": {"latitude": 28.5238, "longitude": 77.3311}, "distance_from_origin_km": 32.1, "layout": "underground", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator", "parking"], "importance_score": 9, "station_type": "commercial", "avg_crowd_multiplier": {"peak": 2.0, "offpeak": 1.2, "weekend": 1.5}},
            {"id": 28, "station_id": "YL28", "name": "Qutab Minar", "display_name": "Qutab Minar", "line": "Yellow", "coordinates": {"latitude": 28.5157, "longitude": 77.3422}, "distance_from_origin_km": 33.9, "layout": "underground", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 8, "station_type": "tourist", "avg_crowd_multiplier": {"peak": 1.4, "offpeak": 0.8, "weekend": 1.8}},
            {"id": 29, "station_id": "YL29", "name": "Chhatarpur", "display_name": "Chhatarpur", "line": "Yellow", "coordinates": {"latitude": 28.5076, "longitude": 77.3533}, "distance_from_origin_km": 35.7, "layout": "elevated", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator", "parking"], "importance_score": 7, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.6, "offpeak": 0.65, "weekend": 0.9}},
            {"id": 30, "station_id": "YL30", "name": "Sultanpur", "display_name": "Sultanpur", "line": "Yellow", "coordinates": {"latitude": 28.4995, "longitude": 77.3644}, "distance_from_origin_km": 37.5, "layout": "elevated", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 6, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.5, "offpeak": 0.6, "weekend": 0.6}},
            {"id": 31, "station_id": "YL31", "name": "Ghitorni", "display_name": "Ghitorni", "line": "Yellow", "coordinates": {"latitude": 28.4914, "longitude": 77.3755}, "distance_from_origin_km": 39.3, "layout": "elevated", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 5, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.3, "offpeak": 0.5, "weekend": 0.5}},
            {"id": 32, "station_id": "YL32", "name": "Arjan Garh", "display_name": "Arjan Garh", "line": "Yellow", "coordinates": {"latitude": 28.4833, "longitude": 77.3866}, "distance_from_origin_km": 41.1, "layout": "elevated", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator"], "importance_score": 5, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.2, "offpeak": 0.5, "weekend": 0.5}},
            {"id": 33, "station_id": "YL33", "name": "Guru Dronacharya", "display_name": "Guru Dronacharya", "line": "Yellow", "coordinates": {"latitude": 28.4752, "longitude": 77.3977}, "distance_from_origin_km": 42.9, "layout": "elevated", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator", "parking"], "importance_score": 6, "station_type": "residential", "avg_crowd_multiplier": {"peak": 1.4, "offpeak": 0.55, "weekend": 0.55}},
            {"id": 34, "station_id": "YL34", "name": "Sikandarpur", "display_name": "Sikandarpur", "line": "Yellow", "coordinates": {"latitude": 28.4671, "longitude": 77.4088}, "distance_from_origin_km": 44.2, "layout": "elevated", "opened_year": 2010, "is_interchange": True, "interchange_lines": ["Rapid Metro"], "facilities": ["elevator", "escalator", "parking"], "importance_score": 8, "station_type": "commercial", "avg_crowd_multiplier": {"peak": 2.0, "offpeak": 0.9, "weekend": 0.8}},
            {"id": 35, "station_id": "YL35", "name": "MG Road", "display_name": "MG Road", "line": "Yellow", "coordinates": {"latitude": 28.4590, "longitude": 77.4199}, "distance_from_origin_km": 45.1, "layout": "elevated", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator", "parking"], "importance_score": 9, "station_type": "commercial", "avg_crowd_multiplier": {"peak": 2.1, "offpeak": 1.0, "weekend": 0.9}},
            {"id": 36, "station_id": "YL36", "name": "IFFCO Chowk", "display_name": "IFFCO Chowk", "line": "Yellow", "coordinates": {"latitude": 28.4509, "longitude": 77.4310}, "distance_from_origin_km": 45.5, "layout": "elevated", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator", "parking"], "importance_score": 9, "station_type": "commercial", "avg_crowd_multiplier": {"peak": 2.2, "offpeak": 1.1, "weekend": 1.0}},
            {"id": 37, "station_id": "YL37", "name": "Huda City Centre(Last Station)", "display_name": "Huda City Centre(Last Station)", "line": "Yellow", "coordinates": {"latitude": 28.4428, "longitude": 77.4421}, "distance_from_origin_km": 45.7, "layout": "elevated", "opened_year": 2010, "is_interchange": False, "interchange_lines": [], "facilities": ["elevator", "escalator", "parking", "bus_terminal"], "importance_score": 9, "station_type": "transport_hub", "avg_crowd_multiplier": {"peak": 2.3, "offpeak": 1.0, "weekend": 0.85}}
        ]
    
    def get_all_stations(self) -> List[Dict]:
        return self.all_stations
    
    def get_stations_by_line(self, line: str) -> List[Dict]:
        return [s for s in self.all_stations if s['line'] == line]
    
    def get_station_by_id(self, station_id: int) -> Optional[Dict]:
        return next((s for s in self.all_stations if s['id'] == station_id), None)
    
    def get_interchange_stations(self) -> List[Dict]:
        return [s for s in self.all_stations if s['is_interchange']]

multi_line_station_service = MultiLineStationService()
